urls.py
from django.conf.urls import patterns, url

from crete_gis.suggest.views import SuggestView

urlpatterns = patterns(
    'crete_gis.suggest.views',
    # Suggest
    url(r'^$', SuggestView.as_view(), name='suggest'),
)

models.py
from django.db import models
import datetime

class Suggestion(models.Model):

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    organization = models.CharField(max_length=100)
    area = models.CharField(max_length=50)
    email = models.EmailField()
    date = models.DateField()
    suggestion = models.TextField()
    

    def __str__(self):
        return "%s - %s" % (self.first_name, self.last_name)

    def __unicode__(self):
        return "%s - %s" % (self.first_name or u'', self.last_name or u'')
     

forms.py
from django import forms
import datetime

class SuggestForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    organization = forms.CharField(required=False)
    area = forms.CharField(required=False)
    email = forms.EmailField(required=False)
    date = forms.DateField(required=False)
    suggestion = forms.CharField(widget=forms.Textarea)

views.py
from django.shortcuts import render_to_response
from django.views.generic.edit import FormView
from crete_gis.suggest.forms import SuggestForm
from crete_gis.suggest.models import Suggestion
from django.template import RequestContext
from django.http import HttpResponse

class SuggestView(FormView):
    # template that is rendered when the form is valid
    template_name = 'suggest/suggestResults.html'

    form_class = SuggestForm
    
    def get(self, request):
        return render_to_response('suggest/suggest.html', RequestContext(request))

    def form_valid(self, form):
        # Get data
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        organization = form.cleaned_data['organization']
        area = form.cleaned_data['area']
        email = form.cleaned_data['email']
        date = form.cleaned_data['date']
        suggestion = form.cleaned_data['suggestion']

        e1 = Suggestion(
                 first_name = first_name,
                 last_name = last_name,
                 organization = organization,
                 area = area,
                 email = email,
                 date = date,
                 suggestion = suggestion,
                )


        e1.save()
        # check if e1 saved
        if e1.pk is None:
            result = 'failed'
            return self.render_to_response({
                'result': result
                })
        else:
            result = 'success'
            return self.render_to_response({
                'result': result
                })

    #def form_invalid(self, form):
    #    return HttpResponse(form.errors)

templates/suggest/base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_outer %}
  {% block body %}
  <h2>Προτάσεις Βελτίωσης και Επέκτασης του Crete - GIS</h2>
     
  <hr>

        <div class="container">

            <div class="row">

                {% block content %}{% endblock %}

            </div>

        </div>

  {% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

templates/suggest/suggest.html
{% extends "suggest/base.html" %}

{% block content %}
     <div class="col-sm-7">

     <h4>Από τη διεπαφή αυτή μπορείτε να προτείνετε ιδέες και εφαρμογές με σκοπό
     τη βελτίωση, την επέκταση και την εξέλιξη του Crete - GIS.</h4>
     <form role="form" action="/suggest/" method="post">{% csrf_token %}
        <div class="form-group">
            <label for="first_name">Όνομα:</label>
            <input id="id_fname" name="first_name" type="text" class="form-control" required></input>
        </div>

        <div class="form-group">
            <label for="last_name">Επίθετο:</label>
            <input id="id_lname" name="last_name" type="text" class="form-control" required></input>
        </div>

        <div class="form-group">
                <label for="organisation">Υπηρεσία:</label>
                <input id="id_organ" name="organization" type="text" class="form-control"></input>
        </div>

        <div class="form-group">
                <label for="area">Περιφερειακή Ενότητα:</label>
                <input id="id_area" name="area" type="text" class="form-control"></input>
        </div>

        <div class="form-group">
                <label for="email">E-mail:</label>
                <input id="id_email" name="email" type="email" class="form-control" required></input>
        </div>

        <div class="form-group">
                <label for="date">Ημερομηνία:</label>
                <input id="id_date" name="date" type="date" class="form-control" required></input>
        </div>

        <div class="form-group">
                <label for="suggestion">Προτάσεις Βελτίωσης:</label>
                <textarea class="form-control" name="suggestion" rows="10"></textarea>
                <!-- <textarea rows="4" cols="50" name="suggestion" ></textarea> -->
        </div>


    

        <input class="btn btn-primary" type="submit" value="Υποβολή" />
    </form>
  </div>

{% endblock %}

templates/suggest/suggestResults.html
{% extends "suggest/base.html" %}

{% block content %}

    {% if result == 'success' %}
        {{ result }}
        <p>Η υποβολή των προτάσεων ήταν επιτυχής !</p>
        <p>Ευχαριστούμε !</p>
    {% endif %}
    {% if result == 'failed' %}
        <p>Η υποβολή των προτάσεων απέτυχε...</p>
        <p>Ξαναπροσπαθήστε αργότερα.</p>
    {% endif %}
{% endblock %}